name: random_user
description: Flutter App Project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #dependencies
  cupertino_icons: ^1.0.2

  #Image Provider package
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9

  #Native splash package
  flutter_native_splash: ^2.3.0

  #State Management
  flutter_riverpod: ^2.4.4
  
  #Navigation package
  go_router: ^13.2.0

  #Database package
  sqflite: ^2.3.2
  path: null

  #Other
  http: null
  fpdart: null
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.1
  json_annotation: ^4.8.1
  flutter_spinkit: ^5.2.0
  introduction_screen: ^3.1.12
  shared_preferences: ^2.2.2
  uuid: null
  lottie: null
  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_logo_foreground.png"


flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo.png"


flutter:
  uses-material-design: true

  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf